### ISSUE TITLE
TypeError when using with the provided Typescript Typings

### ISSUE THREAD

**Issue by tonakai** [commenthol/date-holidays#44] opened 2018-09-19 07:50 UTC
Hi, 
when I try to use the version 1.2.8 via typescript I am getting the following error:
```
> node js/index.js

/Users/asoysal/work/date-holidays-test/js/index.js:4
const h = new date_holidays_1.default();
          ^

TypeError: date_holidays_1.default is not a constructor
```

TS File, which I've based it on the test file in typescript folder:
```ts
import Holidays from "date-holidays"

const h = new Holidays()
```

generated js looks like this:
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var date_holidays_1 = require("date-holidays");
var h = new date_holidays_1.default();
```

**Comment by commenthol** [comment] 2018-09-21 18:56
Hi, I personally don't use typescript in my projects so I can't help with this. Sorry...
@johnolos could you please help here?

**Comment by johnolos** [comment] 2018-11-09 11:53
I'll take a look once I got time. Just saw this now.

For the record, we use this in our code-base and it's working just fine. What TypeScript version are you using?

Our tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es2017", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

**Comment by commenthol** [comment] 2018-12-04 22:33
@tonakai Any news on this issue from your side?

**Comment by commenthol** [comment] 2018-12-27 09:43
@tonakai this problem seams to be unrelated to this project. Could you please confirm by closing this issue?

**Closed** 2019-01-09 07:19 UTC

**Comment by pero5ar** [comment] 2019-10-31 11:41
I'm having the same issue, the problem is that the module is exported as `module.exports = Holiday`, and typings for those kinds of exports should look like `export = Holiday`, `export default Holidays` could be used if the module was exported something like `module.exports = { ...Holiday, default: Holiday }` (the default property needs to have a value if you want to use a default import).

Note that when you do change the typings to `export = ...` you might encounter [this issue](https://stackoverflow.com/questions/48708410/typescript-error-an-export-assignment-cannot-be-used-in-a-module-with-other-exp) and you have to import it as `import * as Holidays from 'date-holidays'`.
Because of the linked issue, you'll probably need to somehow exclude the entire typings file and write your own.

The way I resolved this issue was to fall back to `date-holidays: 1.2.7` (the last version without typings) and wrote my own version of the typings.
There is probably a better way to do this, but going back to an old version wasn't really an issue for my project so it was the easiest for me.

In case someone asks, my tsconfing.json has `module: "commonjs"` and I'm using Typescript version `3.3.3333`
